name: Build Docker Image

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push zsign
        uses: docker/build-push-action@v2
        with:
          context: https://github.com/togettoyou/zsign.git
          push: true
          tags: togettoyou/zsign:latest
      - name: Build and push ipashare
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: togettoyou/ipashare:latest
